# Generated by Django 3.2.7 on 2021-10-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='passcode',
            field=models.CharField(default='123', max_length=20),
            preserve_default=False,
        ),
    ]
