# Generated by Django 3.2.7 on 2021-10-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_passcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('faculty', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=2000)),
            ],
        ),
    ]
