# Generated by Django 3.2.7 on 2021-10-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='status',
            field=models.CharField(choices=[('a', 'available'), ('b', 'borrowed')], default='a', max_length=10),
            preserve_default=False,
        ),
    ]
