# Generated by Django 3.2.7 on 2021-10-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('borrowed', 'borrowed')], max_length=10),
        ),
    ]
