# Generated by Django 3.2.7 on 2021-10-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_books_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='status',
        ),
    ]
