# Generated by Django 3.2.7 on 2021-10-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_books_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='status',
            field=models.CharField(choices=[('Available', 'available'), ('Borrowed', 'borrowed')], default='Available', max_length=10),
            preserve_default=False,
        ),
    ]
