# Generated by Django 3.2.7 on 2021-10-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_books_whoborrowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='whoborrowed',
        ),
    ]
