# Generated by Django 3.2.7 on 2021-10-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_books_whoborrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bookuser',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
