# Generated by Django 3.2.7 on 2021-10-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_users_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
