# Generated by Django 3.2.7 on 2021-10-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_users_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
